### ISSUE TITLE
Serverchan编译失败

### ISSUE THREAD

**Issue by tangyisheng2** [kenzok8/openwrt-packages#152]
最近在尝试自己编译openwrt的ipk，然而编译serverchan一直失败。
编译的步骤为：

1. 首先按照lean的编译步骤1-5下载好repo（https://github.com/coolsnowwolf/lede#%E7%BC%96%E8%AF%91%E5%91%BD%E4%BB%A4%E5%A6%82%E4%B8%8B）
2. 运行make menuconfig在luci-app-serverchan一项打上M标记
3. 运行make package/feeds/kenzo/luci-app-serverchan/compile V=s -j1
4. 出错

下面是log
```
log:
make[1]: Entering directory '/home/user/lede'
make[2]: Entering directory '/home/user/lede/feeds/packages/devel/ninja'
mkdir -p /home/user/lede/dl
SHELL= flock /home/user/lede/tmp/.ninja-1.10.2.tar.gz.flock -c '  	/home/user/lede/scripts/dow
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://codeload.github.com/ninja-build/ninja/tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  208k  100  208k    0     0  86693      0  0:00:02  0:00:02 --:--:-- 86658
. /home/user/lede/include/shell.sh; gzip -dc /home/user/lede/dl/ninja-1.10.2.tar.gz | tar -C /home/
[ ! -d ./src/ ] || cp -fpR ./src/* /home/user/lede/build_dir/hostpkg/ninja-1.10.2
touch /home/user/lede/build_dir/hostpkg/ninja-1.10.2/.prepared2cefbd0330d20221e86a92160723ce0b_6664517399eb
touch /home/user/lede/build_dir/hostpkg/ninja-1.10.2/.configured
cd /home/user/lede/build_dir/hostpkg/ninja-1.10.2 && CXX="g++" CXXFLAGS=" -I/home/user/lede/stagingib -L/home/user/lede/staging_dir/target-x86_64_musl/host/lib" /home/user/lede/staging_dir/host/bin/
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
^CTraceback (most recent call last):
  File "configure.py", line 550, in <module>
    objs = cxx('ninja', variables=cxxvariables)
  File "configure.py", line 287, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
  File "configure.py", line 169, in build
    self._run_command(self._expand(cmd, local_vars))
  File "configure.py", line 194, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Makefile:76: recipe for target '/home/user/lede/build_dir/hostpkg/ninja-1.10.2/.built' failed
make[2]: *** [/home/user/lede/build_dir/hostpkg/ninja-1.10.2/.built] Error 1
time: package/feeds/packages/ninja/host-compile#16.90#1.28#20.92
/home/user/lede/include/toplevel.mk:222: recipe for target 'package/feeds/kenzo/luci-app-serverchan/compile
make: *** [package/feeds/kenzo/luci-app-serverchan/compile] Interrupt

user@esxi:~/lede$ make package/feeds/kenzo/luci-app-serverchan/compile V=s -j1
make[1]: Entering directory '/home/user/lede'
make[2]: Entering directory '/home/user/lede/feeds/packages/devel/ninja'
cd /home/user/lede/build_dir/hostpkg/ninja-1.10.2 && CXX="g++" CXXFLAGS=" -I/home/user/lede/staging_dir/host/include -I/home/user/lede/staging_dir/hostpkg/include -I/home/user/lede/staging_dir/target-x86_64_musl/host/include" LDFLAGS="-L/home/user/lede/staging_dir/host/lib -L/home/user/lede/staging_dir/hostpkg/lib -L/home/user/lede/staging_dir/target-x86_64_musl/host/lib" /home/user/lede/staging_dir/host/bin/python configure.py --bootstrap 
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...
[29/29] LINK ninja
touch /home/user/lede/build_dir/hostpkg/ninja-1.10.2/.built
install -d -m0755 /home/user/lede/staging_dir/hostpkg/bin
install -m0755 /home/user/lede/build_dir/hostpkg/ninja-1.10.2/ninja /home/user/lede/staging_dir/hostpkg/bin/
mkdir -p /home/user/lede/staging_dir/hostpkg/stamp
touch /home/user/lede/build_dir/hostpkg/ninja-1.10.2/.built
touch /home/user/lede/staging_dir/hostpkg/stamp/.ninja_installed
make[2]: Leaving directory '/home/user/lede/feeds/packages/devel/ninja'
time: package/feeds/packages/ninja/host-compile#43.97#3.71#27.31
make[2]: Entering directory '/home/user/lede/feeds/packages/devel/meson'
mkdir -p /home/user/lede/dl
SHELL= flock /home/user/lede/tmp/.meson-0.54.3.tar.gz.flock -c '  	/home/user/lede/scripts/download.pl "/home/user/lede/dl" "meson-0.54.3.tar.gz" "f2bdf4cf0694e696b48261cdd14380fb1d0fe33d24744d8b2df0c12f33ebb662" "" "https://files.pythonhosted.org/packages/source/m/meson"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://files.pythonhosted.org/packages/source/m/meson/meson-0.54.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1651k  100 1651k    0     0  1210k      0  0:00:01  0:00:01 --:--:-- 1210k
. /home/user/lede/include/shell.sh; gzip -dc /home/user/lede/dl/meson-0.54.3.tar.gz | tar -C /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3

Applying ./patches/010-Only-fix-RPATH-if-install_rpath-is-not-empty.patch using plaintext: 
patching file mesonbuild/minstall.py
touch /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/.preparedb47e5e2838ddebc53177ade9e93d4b13_6664517399ebbbc92a37c5bb081b5c53
touch /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/.configured
touch /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/.built
install -d -m0755 /home/user/lede/staging_dir/hostpkg/lib/meson
cp -fpR /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/* /home/user/lede/staging_dir/hostpkg/lib/meson/
mkdir -p /home/user/lede/staging_dir/hostpkg/stamp
touch /home/user/lede/build_dir/hostpkg/pypi/meson-0.54.3/.built
touch /home/user/lede/staging_dir/hostpkg/stamp/.meson_installed
make[2]: Leaving directory '/home/user/lede/feeds/packages/devel/meson'
time: package/feeds/packages/meson/host-compile#0.40#0.36#2.03
make[2]: Entering directory '/home/user/lede/package/libs/toolchain'
touch /home/user/lede/build_dir/target-x86_64_musl/toolchain/.prepared_6963ee5e84890707031cb8fe8c29cf8f_6664517399ebbbc92a37c5bb081b5c53_check
mkdir -p /home/user/lede/build_dir/target-x86_64_musl/toolchain
touch /home/user/lede/build_dir/target-x86_64_musl/toolchain/.prepared_6963ee5e84890707031cb8fe8c29cf8f_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/user/lede/build_dir/target-x86_64_musl/toolchain/.configured_*
rm -f /home/user/lede/staging_dir/target-x86_64_musl/stamp/.toolchain_installed
(cd /home/user/lede/build_dir/target-x86_64_musl/toolchain/./; if [ -x ./configure ]; then find /home/user/lede/build_dir/target-x86_64_musl/toolchain/ -name config.guess | xargs -r chmod u+w; find /home/user/lede/build_dir/target-x86_64_musl/toolchain/ -name config.guess | xargs -r -n1 cp --remove-destination /home/user/lede/scripts/config.guess; find /home/user/lede/build_dir/target-x86_64_musl/toolchain/ -name config.sub | xargs -r chmod u+w; find /home/user/lede/build_dir/target-x86_64_musl/toolchain/ -name config.sub | xargs -r -n1 cp --remove-destination /home/user/lede/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/user/lede/build_dir/target-x86_64_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/user/lede/build_dir/target-x86_64_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/user/lede/build_dir/target-x86_64_musl/toolchain=toolchain -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/user/lede/staging_dir/target-x86_64_musl/usr/include -I/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include " LDFLAGS="-L/home/user/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/user/lede/staging_dir/target-x86_64_musl/lib -L/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro "   ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/user/lede/build_dir/target-x86_64_musl/toolchain/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/user/lede/build_dir/target-x86_64_musl/toolchain/.built
touch /home/user/lede/build_dir/target-x86_64_musl/toolchain/.built_check
touch /home/user/lede/build_dir/target-x86_64_musl/toolchain/.built
rm -rf /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
mkdir -p /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
install -d -m0755 /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/ld-musl-*.so* /home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/home/user/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/ld-musl-*.so*': No such file or directory
Makefile:750: recipe for target '/home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed' failed
make[2]: *** [/home/user/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/home/user/lede/package/libs/toolchain'
time: package/libs/toolchain/compile#0.14#0.06#0.24
package/Makefile:111: recipe for target 'package/libs/toolchain/compile' failed
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/home/user/lede'
/home/user/lede/include/toplevel.mk:222: recipe for target 'package/feeds/kenzo/luci-app-serverchan/compile' failed
make: *** [package/feeds/kenzo/luci-app-serverchan/compile] Error 2

```
感谢帮助~!

**Comment by kenzok8** [comment]
自动巡检：该 Issue 长时间未更新（>=180 天）且无后续反馈，先关闭以便集中处理当前问题。

如问题仍存在，请按最新源码重新复现后提交新 Issue，并附：
- 固件版本与目标架构
- 完整编译/运行日志（从第一个报错开始）
- 复现步骤

Auto triage: this issue has been inactive for >=180 days with no follow-up, so it is being closed for backlog cleanup.
If the issue still exists, please open a new issue with updated logs and reproduction steps.

**Comment by kenzok8** [comment]
Closed by automated stale triage.
